# Generated by Django 6.0.3 on 2026-03-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='is_active',
        ),
        migrations.AddField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('completed', 'Completed')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('morning', 'Morning Shift'), ('night', 'Night Shift')], max_length=10),
        ),
    ]
