# Generated by Django 6.0.3 on 2026-03-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_shift_is_active_shift_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
