# Generated by Django 6.0.3 on 2026-03-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_shift_is_archived'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
