# Generated by Django 6.0.3 on 2026-03-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='staff_role',
            field=models.CharField(choices=[('none', 'None (Customer/Manager)'), ('computer', 'Computer/Front Desk'), ('kitchen', 'Kitchen Control'), ('cooker', 'Cooker'), ('cleaner', 'Cleaner'), ('delivery', 'Delivery Boy')], default='none', max_length=15),
        ),
    ]
