# Generated by Django 6.0.3 on 2026-03-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('manager', 'Manager'), ('owner', 'Owner')], default='customer', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='staff_role',
            field=models.CharField(choices=[('none', 'None (Customer/Admin)'), ('computer', 'Computer/Front Desk'), ('kitchen', 'Kitchen Control'), ('cooker', 'Cooker'), ('cleaner', 'Cleaner'), ('delivery', 'Delivery Boy')], default='none', max_length=15),
        ),
    ]
