# Generated by Django 6.0.3 on 2026-03-14 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_instructions_orderitem_special_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='special_note',
            new_name='instructions',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='processed_by',
        ),
        migrations.AddField(
            model_name='order',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_processed', to=settings.AUTH_USER_MODEL),
        ),
    ]
