# Generated by Django 6.0.3 on 2026-03-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
