# Generated by Django on 2026-03-20 22:15
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_is_internal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_internal',
        ),
    ]
