# Generated by Django 6.0.3 on 2026-03-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_system_active', models.BooleanField(default=True, help_text='If disabled, staff can process orders without starting a shift.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'General Settings',
                'verbose_name_plural': 'General Settings',
            },
        ),
    ]
