# Generated by Django 6.0.3 on 2026-03-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralSettings',
        ),
    ]
